=== mrrishit909/atlas-human-mobility/data/contracts/daily.schema.json
{
 "$schema": "https://json-schema.org/draft/2020-12/schema",
 "additionalProperties": true,
 "properties": {
  "date": {
   "items": {
    "type": "string"
   },
   "maxItems": 366,
   "minItems": 366,
   "type": "array"
  },
  "prcp_mm": {
   "items": {
    "type": [
     "number",
     "null"
    ]
   },
   "maxItems": 366,
   "minItems": 366,
   "type": "array"
  },
  "schema_version": {
   "const": "v1"
  },
  "snow_mm": {
   "items": {
    "type": [
     "number",
     "null"
    ]
   },
   "maxItems": 366,
   "minItems": 366,
   "type": "array"
  },
  "station": {
   "type": "string"
  },
  "tags": {
   "additionalProperties": {
    "pattern": "^(OBSERVED|DERIVED|PREDICTED|SIMULATED)(/(OBSERVED|DERIVED|PREDICTED|SIMULATED))*$",
    "type": "string"
   },
   "minProperties": 1,
   "type": "object"
  },
  "tmax_c": {
   "items": {
    "type": [
     "number",
     "null"
    ]
   },
   "maxItems": 366,
   "minItems": 366,
   "type": "array"
  },
  "tmin_c": {
   "items": {
    "type": [
     "number",
     "null"
    ]
   },
   "maxItems": 366,
   "minItems": 366,
   "type": "array"
  },
  "trips": {
   "additionalProperties": true,
   "properties": {
    "fhvhv": {
     "items": {
      "type": "integer"
     },
     "maxItems": 366,
     "minItems": 366,
     "type": "array"
    },
    "green": {
     "items": {
      "type": "integer"
     },
     "maxItems": 366,
     "minItems": 366,
     "type": "array"
    },
    "yellow": {
     "items": {
      "type": "integer"
     },
     "maxItems": 366,
     "minItems": 366,
     "type": "array"
    }
   },
   "required": [
    "yellow",
    "green",
    "fhvhv"
   ],
   "type": "object"
  },
  "units": {
   "type": "object"
  }
 },
 "required": [
  "schema_version",
  "tags",
  "station",
  "units",
  "date",
  "trips",
  "prcp_mm",
  "tmax_c",
  "tmin_c",
  "snow_mm"
 ],
 "title": "daily",
 "type": "object"
}

=== mrrishit909/atlas-human-mobility/site/public/data/daily.json
{"date":["2024-01-01","2024-01-02","2024-01-03","2024-01-04","2024-01-05","2024-01-06","2024-01-07","2024-01-08","2024-01-09","2024-01-10","2024-01-11","2024-01-12","2024-01-13","2024-01-14","2024-01-15","2024-01-16","2024-01-17","2024-01-18","2024-01-19","2024-01-20","2024-01-21","2024-01-22","2024-01-23","2024-01-24","2024-01-25","2024-01-26","2024-01-27","2024-01-28","2024-01-29","2024-01-30","2024-01-31","2024-02-01","2024-02-02","2024-02-03","2024-02-04","2024-02-05","2024-02-06","2024-02-07","2024-02-08","2024-02-09","2024-02-10","2024-02-11","2024-02-12","2024-02-13","2024-02-14","2024-02-15","2024-02-16","2024-02-17","2024-02-18","2024-02-19","2024-02-20","2024-02-21","2024-02-22","2024-02-23","2024-02-24","2024-02-25","2024-02-26","2024-02-27","2024-02-28","2024-02-29","2024-03-01","2024-03-02","2024-03-03","2024-03-04","2024-03-05","2024-03-06","2024-03-07","2024-03-08","2024-03-09","2024-03-10","2024-03-11","2024-03-12","2024-03-13","2024-03-14","2024-03-15","2024-03-16","2024-03-17","2024-03-18","2024-03-19","2024-03-20","2024-03-21","2024-03-22","2024-03-23","2024-03-24","2024-03-25","2024-03-26","2024-03-27","2024-03-28","2024-03-29","2024-03-30","2024-03-31","2024-04-01","2024-04-02","2024-04-03","2024-04-04","2024-04-05","2024-04-06","2024-04-07","2024-04-08","2024-04-09","2024-04-10","2024-04-11","2024-04-12","2024-04-13","2024-04-14","2024-04-15","2024-04-16","2024-04-17","2024-04-18","2024-04-19","2024-04-20","2024-04-21","2024-04-22","2024-04-23","2024-04-24","2024-04-25","2024-04-26","2024-04-27","2024-04-28","2024-04-29","2024-04-30","2024-05-01","2024-05-02","2024-05-03","2024-05-04","2024-05-05","2024-05-06","2024-05-07","2024-05-08","2024-05-09","2024-05-10","2024-05-11","2024-05-12","2024-05-13","2024-05-14","2024-05-15","2024-05-16","2024-05-17","2024-05-18","2024-05-19","2024-05-20","2024-05-21","2024-05-22","2024-05-23","2024-05-24","2024-05-25","2024-05-26","2024-05-27","2024-05-28","2024-05-29","2024-05-30","2024-05-31","2024-06-01","2024-06-02","2024-06-03","2024-06-04","2024-06-05","2024-06-06","2024-06-07","2024-06-08","2024-06-09","2024-06-10","2024-06-11","2024-06-12","2024-06-13","2024-06-14","2024-06-15","2024-06-16","2024-06-17","2024-06-18","2024-06-19","2024-06-20","2024-06-21","2024-06-22","2024-06-23","2024-06-24","2024-06-25","2024-06-26","2024-06-27","2024-06-28","2024-06-29","2024-06-30","2024-07-01","2024-07-02","2024-07-03","2024-07-04","2024-07-05","2024-07-06","2024-07-07","2024-07-08","2024-07-09","2024-07-10","2024-07-11","2024-07-12","2024-07-13","2024-07-14","2024-07-15","2024-07-16","2024-07-17","2024-07-18","2024-07-19","2024-07-20","2024-07-21","2024-07-22","2024-07-23","2024-07-24","2024-07-25","2024-07-26","2024-07-27","2024-07-28","2024-07-29","2024-07-30","2024-07-31","2024-08-01","2024-08-02","2024-08-03","2024-08-04","2024-08-05","2024-08-06","2024-08-07","2024-08-08","2024-08-09","2024-08-10","2024-08-11","2024-08-12","2024-08-13","2024-08-14","2024-08-15","2024-08-16","2024-08-17","2024-08-18","2024-08-19","2024-08-20","2024-08-21","2024-08-22","2024-08-23","2024-08-24","2024-08-25","2024-08-26","2024-08-27","2024-08-28","2024-08-29","2024-08-30","2024-08-31","2024-09-01","2024-09-02","2024-09-03","2024-09-04","2024-09-05","2024-09-06","2024-09-07","2024-09-08","2024-09-09","2024-09-10","2024-09-11","2024-09-12","2024-09-13","2024-09-14","2024-09-15","2024-09-16","2024-09-17","2024-09-18","2024-09-19","2024-09-20","2024-09-21","2024-09-22","2024-09-23","2024-09-24","2024-09-25","2024-09-26","2024-09-27","2024-09-28","2024-09-29","2024-09-30","2024-10-01","2024-10-02","2024-10-03","2024-10-04","2024-10-05","2024-10-06","2024-10-07","2024-10-08","2024-10-09","2024-10-10","2024-10-11","2024-10-12","2024-10-13","2024-10-14","2024-10-15","2024-10-16","2024-10-17","2024-10-18","2024-10-19","2024-10-20","2024-10-21","2024-10-22","2024-10-23","2024-10-24","2024-10-25","2024-10-26","2024-10-27","2024-10-28","2024-10-29","2024-10-30","2024-10-31","2024-11-01","2024-11-02","2024-11-03","2024-11-04","2024-11-05","2024-11-06","2024-11-07","2024-11-08","2024-11-09","2024-11-10","2024-11-11","2024-11-12","2024-11-13","2024-11-14","2024-11-15","2024-11-16","2024-11-17","2024-11-18","2024-11-19","2024-11-20","2024-11-21","2024-11-22","2024-11-23","2024-11-24","2024-11-25","2024-11-26","2024-11-27","2024-11-28","2024-11-29","2024-11-30","2024-12-01","2024-12-02","2024-12-03","2024-12-04","2024-12-05","2024-12-06","2024-12-07","2024-12-08","2024-12-09","2024-12-10","2024-12-11","2024-12-12","2024-12-13","2024-12-14","2024-12-15","2024-12-16","2024-12-17","2024-12-18","2024-12-19","2024-12-20","2024-12-21","2024-12-22","2024-12-23","2024-12-24","2024-12-25","2024-12-26","2024-12-27","2024-12-28","2024-12-29","2024-12-30","2024-12-31"],"prcp_mm":[0.8,0.0,0.0,0.0,0.0,10.4,6.1,0.0,43.9,5.6,0.0,2.0,20.6,0.0,1.0,7.1,0.0,0.0,1.0,0.0,0.0,0.0,1.3,1.3,6.1,4.8,0.0,20.8,1.3,0.0,0.0,0.0,8.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19.6,0.0,0.0,0.0,4.6,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.3,13.2,4.3,0.0,0.0,32.3,0.0,0.0,10.9,30.5,2.8,0.0,38.9,0.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3,0.0,0.0,93.0,0.0,0.0,0.0,1.5,17.8,0.0,1.0,0.5,0.3,22.1,39.4,5.3,0.0,0.0,0.0,0.0,0.0,0.0,6.1,8.6,0.3,2.5,0.0,0.0,0.5,0.3,0.0,1.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3,0.5,0.8,0.5,0.0,0.0,0.0,7.9,0.0,0.0,5.3,0.0,5.8,0.0,3.8,0.0,0.8,7.1,6.9,0.0,1.0,0.0,0.0,0.0,0.0,19.8,0.0,0.0,0.0,24.4,0.0,16.5,4.6,0.0,0.0,0.0,0.0,0.0,0.0,19.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.8,0.0,0.0,0.0,2.0,5.8,0.0,1.5,4.6,0.0,0.0,0.0,1.0,2.5,1.3,0.0,0.0,0.0,0.0,2.8,1.5,52.3,0.0,3.0,0.0,37.1,0.0,0.0,0.0,0.0,0.3,2.8,0.0,0.0,0.0,0.0,0.0,1.3,0.0,0.8,0.0,13.2,18.5,4.3,0.0,52.8,3.3,9.1,2.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,58.2,6.4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,7.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,4.6,6.6,19.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39.9,13.5,0.5,0.0,0.0,4.8,0.0,21.8,0.0,0.0,0.0,0.0,0.0,0.3,2.3,0.0,0.0,0.0,4.6,6.6,21.6,0.0,0.0,0.0,1.5,23.1,0.5,8.1,1.3,1.0,3.8,0.0,0.0,2.5,0.0,0.0,0.0,14.2,4.1,9.4,10.2],"schema_version":"v1","snow_mm":[0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,33.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,81.0,0.0,0.0,0.0,51.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.0,0.0,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"station":"USW00094728 Central Park (NOAA GHCN-Daily)","tags":{"trips":"OBSERVED","weather":"OBSERVED"},"tmax_c":[8.3,5.6,6.1,7.2,2.8,3.3,3.3,7.2,13.9,13.9,8.3,10.0,15.6,6.7,-1.6,0.0,-4.3,1.1,0.0,-3.2,-0.5,3.3,4.4,8.9,15.0,7.8,9.4,6.7,4.4,3.3,4.4,7.8,7.8,6.1,7.8,7.2,5.6,8.9,11.7,12.8,15.6,13.3,8.9,5.0,3.3,3.9,6.1,2.2,4.4,5.0,4.4,6.1,7.2,8.3,6.7,5.0,12.8,12.8,16.7,6.1,8.9,12.8,20.0,15.0,9.4,11.7,12.2,13.9,9.4,10.6,11.1,18.9,16.7,23.3,22.8,16.1,17.2,10.6,8.9,13.9,6.1,7.8,10.0,8.9,11.7,11.7,11.1,10.6,13.3,16.7,16.7,12.2,10.6,7.2,11.7,10.0,12.2,15.6,20.6,26.7,19.4,16.1,17.2,13.3,23.9,27.8,22.8,16.7,10.0,15.6,21.7,12.2,17.8,18.3,23.3,15.6,18.3,17.8,26.1,30.6,18.9,26.7,26.1,18.3,17.2,12.2,23.3,26.7,28.9,21.1,13.3,17.8,13.9,18.3,22.2,17.8,17.8,22.2,20.6,23.9,23.3,28.3,28.9,26.1,28.9,27.2,27.8,22.8,26.1,24.4,21.7,23.9,28.3,27.2,30.0,26.1,26.1,27.2,27.8,24.4,23.3,23.9,22.8,24.4,28.9,29.4,26.7,25.6,28.3,30.0,31.7,32.8,34.4,33.9,33.3,26.7,32.2,33.9,28.9,26.1,26.1,29.4,27.2,30.0,28.3,31.7,32.2,33.3,33.9,35.0,31.7,32.8,31.7,28.9,30.6,32.2,32.8,34.4,32.2,30.0,28.3,28.3,31.1,28.9,27.2,27.2,28.3,28.9,30.6,31.7,28.9,31.1,31.7,35.0,33.3,33.9,28.3,32.2,32.2,22.2,21.1,26.7,29.4,26.7,27.2,27.2,29.4,30.0,30.6,26.1,27.2,28.9,22.2,22.8,24.4,26.7,28.3,29.4,29.4,30.0,32.8,27.8,23.3,25.0,27.2,26.1,23.3,25.0,25.0,25.6,24.4,20.6,23.9,25.6,26.1,26.7,27.8,28.3,26.7,25.0,26.1,23.9,28.9,27.2,26.1,23.3,19.4,20.0,20.0,23.3,23.3,20.0,17.2,22.2,20.6,20.0,22.2,22.8,23.9,21.7,23.9,20.0,20.0,16.7,20.0,23.3,20.6,18.9,13.9,15.0,14.4,18.9,21.7,22.8,26.1,27.2,23.9,20.6,16.7,17.8,13.9,16.1,17.2,24.4,27.2,26.1,15.6,12.2,14.4,22.8,26.7,22.8,20.6,12.2,14.4,20.0,15.0,10.0,8.3,14.4,16.7,17.2,18.9,15.6,15.6,12.2,4.4,9.4,11.7,12.2,14.4,11.1,9.4,8.3,3.9,3.3,3.9,5.6,5.6,4.4,1.1,5.0,12.8,10.6,10.0,15.6,5.0,0.6,1.1,5.0,11.1,15.0,11.7,7.2,2.8,0.6,-6.0,-0.5,3.9,1.7,2.2,6.7,12.2,15.6,14.4,11.7],"tmin_c":[1.7,-1.6,1.1,-2.1,-3.2,-0.5,1.1,2.2,2.2,6.7,5.0,4.4,1.7,-3.2,-4.9,-5.5,-8.2,-5.5,-3.2,-7.7,-6.6,-3.8,1.1,3.3,7.8,5.6,6.1,2.8,2.2,1.7,1.1,2.8,3.3,0.0,-0.5,0.0,-1.6,0.6,2.8,6.1,8.3,6.1,2.8,0.6,-1.6,-2.7,2.2,-2.7,-3.2,-0.5,-3.2,-1.0,1.7,5.6,-2.1,-4.9,1.7,4.4,6.7,-0.5,-1.0,5.6,8.9,7.8,5.6,8.3,6.7,4.4,5.0,2.8,1.7,6.1,8.9,7.8,10.6,8.3,8.9,3.3,2
