=== mrrishit909/atlas-human-mobility/data/contracts/network.schema.json
{
 "$schema": "https://json-schema.org/draft/2020-12/schema",
 "additionalProperties": true,
 "properties": {
  "method": {
   "type": "string"
  },
  "n_edges": {
   "type": "integer"
  },
  "nodes": {
   "items": {
    "additionalProperties": true,
    "properties": {
     "betweenness": {
      "type": "number"
     },
     "cluster": {
      "type": [
       "integer",
       "null"
      ]
     },
     "in_strength": {
      "type": "integer"
     },
     "out_strength": {
      "type": "integer"
     },
     "pagerank": {
      "type": "number"
     },
     "zone": {
      "type": "integer"
     }
    },
    "required": [
     "zone",
     "pagerank",
     "in_strength",
     "out_strength",
     "betweenness",
     "cluster"
    ],
    "type": "object"
   },
   "maxItems": 263,
   "minItems": 263,
   "type": "array"
  },
  "schema_version": {
   "const": "v1"
  },
  "tags": {
   "additionalProperties": {
    "pattern": "^(OBSERVED|DERIVED|PREDICTED|SIMULATED)(/(OBSERVED|DERIVED|PREDICTED|SIMULATED))*$",
    "type": "string"
   },
   "minProperties": 1,
   "type": "object"
  }
 },
 "required": [
  "schema_version",
  "tags",
  "method",
  "n_edges",
  "nodes"
 ],
 "title": "network",
 "type": "object"
}

=== mrrishit909/atlas-human-mobility/site/public/data/network.json
{"method":"directed OD graph, known zones, o != d, pairs >= 11 trips; PageRank alpha=.85 weight=trips; betweenness exact, edge length = 1/trips, normalized","n_edges":59313,"nodes":[{"betweenness":0.0,"cluster":null,"in_strength":1802059,"out_strength":12,"pagerank":0.005808624393781713,"zone":1},{"betweenness":0.0,"cluster":null,"in_strength":427,"out_strength":330,"pagerank":0.0005808921894118107,"zone":2},{"betweenness":0.0,"cluster":1,"in_strength":455652,"out_strength":442377,"pagerank":0.0025773970123403912,"zone":3},{"betweenness":0.0,"cluster":2,"in_strength":788893,"out_strength":795531,"pagerank":0.0026388191856029615,"zone":4},{"betweenness":0.007531221666520429,"cluster":1,"in_strength":58285,"out_strength":62984,"pagerank":0.001594174533943911,"zone":5},{"betweenness":0.0,"cluster":1,"in_strength":128109,"out_strength":120388,"pagerank":0.001971728737290455,"zone":6},{"betweenness":0.044207539995905355,"cluster":0,"in_strength":2039915,"out_strength":1986125,"pagerank":0.007712955324874933,"zone":7},{"betweenness":0.0,"cluster":0,"in_strength":10388,"out_strength":9508,"pagerank":0.0006133521009028357,"zone":8},{"betweenness":0.0,"cluster":1,"in_strength":195792,"out_strength":184029,"pagerank":0.001556234188014234,"zone":9},{"betweenness":0.0,"cluster":1,"in_strength":642055,"out_strength":696022,"pagerank":0.003276175848549843,"zone":10},{"betweenness":0.0,"cluster":1,"in_strength":243234,"out_strength":242080,"pagerank":0.0017677594944251166,"zone":11},{"betweenness":0.0,"cluster":0,"in_strength":70371,"out_strength":42276,"pagerank":0.0007517730643495774,"zone":12},{"betweenness":0.0,"cluster":0,"in_strength":1259335,"out_strength":1246582,"pagerank":0.0037819630930287064,"zone":13},{"betweenness":0.12430171682606535,"cluster":1,"in_strength":1000907,"out_strength":925043,"pagerank":0.0052639024381354385,"zone":14},{"betweenness":0.0,"cluster":1,"in_strength":158323,"out_strength":146640,"pagerank":0.0013701236063767956,"zone":15},{"betweenness":0.01643707408382323,"cluster":1,"in_strength":378102,"out_strength":346998,"pagerank":0.002630301664950477,"zone":16},{"betweenness":0.011304144365476295,"cluster":0,"in_strength":1914769,"out_strength":1822820,"pagerank":0.006865786093418003,"zone":17},{"betweenness":0.02225731917756135,"cluster":1,"in_strength":960412,"out_strength":966811,"pagerank":0.004540198964566346,"zone":18},{"betweenness":0.0,"cluster":1,"in_strength":161254,"out_strength":149046,"pagerank":0.001386733990694996,"zone":19},{"betweenness":0.003802170161738469,"cluster":1,"in_strength":657807,"out_strength":632952,"pagerank":0.0032911706013029835,"zone":20},{"betweenness":0.001272264631043257,"cluster":1,"in_strength":533720,"out_strength":538011,"pagerank":0.0032205215217062312,"zone":21},{"betweenness":0.02273990231347431,"cluster":1,"in_strength":672236,"out_strength":678980,"pagerank":0.0039034387492998587,"zone":22},{"betweenness":0.08467140475563745,"cluster":1,"in_strength":335580,"out_strength":278830,"pagerank":0.004603078711337394,"zone":23},{"betweenness":0.0,"cluster":1,"in_strength":442487,"out_strength":433662,"pagerank":0.0018236712133846205,"zone":24},{"betweenness":0.002091193588956158,"cluster":0,"in_strength":1280378,"out_strength":1368232,"pagerank":0.004763714165719512,"zone":25},{"betweenness":0.05324500599572987,"cluster":1,"in_strength":762224,"out_strength":703609,"pagerank":0.004095961077405103,"zone":26},{"betweenness":0.0,"cluster":0,"in_strength":25977,"out_strength":16469,"pagerank":0.0007681815408991703,"zone":27},{"betweenness":0.0,"cluster":1,"in_strength":527048,"out_strength":527274,"pagerank":0.0028290068981796208,"zone":28},{"betweenness":0.0,"cluster":1,"in_strength":439886,"out_strength":404126,"pagerank":0.0028309428950710584,"zone":29},{"betweenness":0.0,"cluster":2,"in_strength":14052,"out_strength":13117,"pagerank":0.0007162095253087106,"zone":30},{"betweenness":0.0,"cluster":0,"in_strength":116381,"out_strength":95707,"pagerank":0.001029663279616832,"zone":31},{"betweenness":0.003685180310608055,"cluster":1,"in_strength":508037,"out_strength":518055,"pagerank":0.0027420758446589804,"zone":32},{"betweenness":7.311865695650902e-05,"cluster":0,"in_strength":1162802,"out_strength":1117981,"pagerank":0.004170108758435359,"zone":33},{"betweenness":0.0,"cluster":0,"in_strength":271848,"out_strength":223866,"pagerank":0.0014480480750435195,"zone":34},{"betweenness":0.0,"cluster":1,"in_strength":1165431,"out_strength":1248093,"pagerank":0.004866552392282797,"zone":35},{"betweenness":0.0017109765727823113,"cluster":2,"in_strength":1744262,"out_strength":1763358,"pagerank":0.0062808485373525335,"zone":36},{"betweenness":0.03490684683103741,"cluster":2,"in_strength":2429028,"out_strength":2326427,"pagerank":0.008402586031276226,"zone":37},{"betweenness":0.0,"cluster":1,"in_strength":209165,"out_strength":219324,"pagerank":0.001526613419447864,"zone":38},{"betweenness":0.041706881927992746,"cluster":1,"in_strength":1217874,"out_strength":1265413,"pagerank":0.005275419860467394,"zone":39},{"betweenness":0.0,"cluster":0,"in_strength":572509,"out_strength":546755,"pagerank":0.002467032569450413,"zone":40},{"betweenness":0.002559152993477816,"cluster":0,"in_strength":1584450,"out_strength":1579413,"pagerank":0.005523509160157423,"zone":41},{"betweenness":0.10425258108859056,"cluster":1,"in_strength":1916348,"out_strength":1951540,"pagerank":0.0069346030323998295,"zone":42},{"betweenness":0.0,"cluster":0,"in_strength":935530,"out_strength":982950,"pagerank":0.0029101174458155093,"zone":43},{"betweenness":0.0,"cluster":1,"in_strength":66672,"out_strength":60217,"pagerank":0.001676655092099872,"zone":44},{"betweenness":0.0,"cluster":2,"in_strength":641292,"out_strength":646756,"pagerank":0.002328423749911017,"zone":45},{"betweenness":0.0,"cluster":0,"in_strength":50804,"out_strength":39232,"pagerank":0.0008199805093195688,"zone":46},{"betweenness":0.0,"cluster":1,"in_strength":709068,"out_strength":731549,"pagerank":0.0033917287855566103,"zone":47},{"betweenness":0.04423678745868796,"cluster":2,"in_strength":2813363,"out_strength":3106225,"pagerank":0.007923060715370498,"zone":48},{"betweenness":0.0,"cluster":0,"in_strength":1471490,"out_strength":1403017,"pagerank":0.005251277025745458,"zone":49},{"betweenness":0.0,"cluster":1,"in_strength":1540101,"out_strength":1532337,"pagerank":0.004545954215927578,"zone":50},{"betweenness":0.010251235705302566,"cluster":1,"in_strength":756934,"out_strength":721620,"pagerank":0.004019055361946825,"zone":51},{"betweenness":0.0,"cluster":0,"in_strength":348534,"out_strength":375573,"pagerank":0.0017034830824371665,"zone":52},{"betweenness":0.0,"cluster":1,"in_strength":341641,"out_strength":312968,"pagerank":0.002096069154989965,"zone":53},{"betweenness":0.0,"cluster":0,"in_strength":145513,"out_strength":136768,"pagerank":0.001052854345106532,"zone":54},{"betweenness":0.0,"cluster":1,"in_strength":523908,"out_strength":491781,"pagerank":0.0031398747609085896,"zone":55},{"betweenness":1.4623731391301805e-05,"cluster":1,"in_strength":607928,"out_strength":664452,"pagerank":0.002999163986722286,"zone":56},{"betweenness":0.0,"cluster":1,"in_strength":47068,"out_strength":49894,"pagerank":0.0007678752749745689,"zone":57},{"betweenness":0.0,"cluster":1,"in_strength":74678,"out_strength":72196,"pagerank":0.0009177569600527318,"zone":58},{"betweenness":0.0,"cluster":1,"in_strength":30616,"out_strength":25862,"pagerank":0.0006977209353944236,"zone":59},{"betweenness":0.0,"cluster":1,"in_strength":464166,"out_strength":494122,"pagerank":0.002449810899945862,"zone":60},{"betweenness":0.09287531806615776,"cluster":0,"in_strength":2970273,"out_strength":2764039,"pagerank":0.010653036035323641,"zone":61},{"betweenness":0.0,"cluster":0,"in_strength":827634,"out_strength":819883,"pagerank":0.003460060769519683,"zone":62},{"betweenness":0.0,"cluster":1,"in_strength":663748,"out_strength":670642,"pagerank":0.0031183706206641035,"zone":63},{"betweenness":0.0,"cluster":1,"in_strength":114218,"out_strength":96890,"pagerank":0.0011589831261909528,"zone":64},{"betweenness":0.001798718961130122,"cluster":0,"in_strength":1078872,"out_strength":1172417,"pagerank":0.004010757428753629,"zone":65},{"betweenness":0.0,"cluster":0,"in_strength":838023,"out_strength":897539,"pagerank":0.0030671450405857508,"zone":66},{"betweenness":0.0,"cluster":1,"in_strength":402350,"out_strength":389485,"pagerank":0.0024549829905588516,"zone":67},{"betweenness":0.00835015062443333,"cluster":0,"in_strength":3533036,"out_strength":3474206,"pagerank":0.009565906841000116,"zone":68},{"betweenness":0.002983241203825568,"cluster":1,"in_strength":1120669,"out_strength":1096917,"pagerank":0.004830138055860115,"zone":69},{"betweenness":0.0,"cluster":1,"in_strength":455566,"out_strength":685426,"pagerank":0.002343205954639492,"zone":70},{"betweenness":0.0,"cluster":1,"in_strength":941145,"out_strength":939635,"pagerank":0.004061491470258331,"zone":71},{"betweenness":1.4623731391301805e-05,"cluster":1,"in_strength":1064000,"out_strength":1099674,"pagerank":0.004484448065767183,"zone":72},{"betweenness":0.0,"cluster":1,"in_strength":222958,"out_strength":226262,"pagerank":0.0016193326695702992,"zone":73},{"betweenness":0.08211225176215964,"cluster":1,"in_strength":1792486,"out_strength":1774404,"pagerank":0.006327908782914779,"zone":74},{"betweenness":0.08285806206311602,"cluster":1,"in_strength":1962885,"out_strength":1746074,"pagerank":0.0064395309040875945,"zone":75},{"betweenness":0.053361995846860286,"cluster":1,"in_strength":1817349,"out_strength":1779429,"pagerank":0.0076334456660516695,"zone":76},{"betweenness":0.0,"cluster":1,"in_strength":653069,"out_strength":652778,"pagerank":0.0029984073045175937,"zone":77},{"betweenness":0.01959580006434442,"cluster":1,"in_strength":915971,"out_strength":935509,"pagerank":0.004332161868665154,"zone":78},{"betweenness":0.044397648503992276,"cluster":2,"in_strength":3301984,"out_strength":3853064,"pagerank":0.008984784049843273,"
